// svelte-app/src/lib/modules/chat/components/Chat/MessagesContainer/ScrollToBottomButton.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { CaretDown } from 'phosphor-svelte';

	export let container: HTMLUListElement;

	let isVisible = false;

	onMount(() => {
		const handleScroll = () => {
			if (container) {
				const isScrolledToBottom = container.scrollHeight - container.clientHeight <= container.scrollTop + 1;
				isVisible = !isScrolledToBottom;
			}
		};

		container?.addEventListener('scroll', handleScroll);

		return () => {
			container.removeEventListener('scroll', handleScroll);
		};
	});

	function scrollToBottom() {
		container.scroll({
			top: container.scrollHeight,
			behavior: 'smooth',
		});
	}
</script>

{#if isVisible}
	<button
		type="button"
		title="Scroll to bottom"
		on:click|stopPropagation={scrollToBottom}
		class="absolute bottom-20 right-6 z-20 flex items-center justify-center bg-purple-400 outline-none focus:outline-purple-500 focus:ring-0 rounded-full min-w-[2.5rem] min-h-[2.5rem] max-w-[2.5rem] max-h-[2.5rem] mt-auto ml-auto p-2"
	>
		<CaretDown class="text-white" />
	</button>
{/if}

// web/src/app/products/chats/components/Chat/MessagesContainer/ScrollToBottomButton.tsx
import { CaretDown } from '@phosphor-icons/react';
import { useEffect, RefObject, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';

interface Props {
	messageContainerRef: RefObject<HTMLUListElement>;
}

export function ScrollToBottomButton({ messageContainerRef }: Props) {
	const [isVisible, setIsVisible] = useState(false);

	useEffect(() => {
		const containerRef = messageContainerRef.current;

		if (!containerRef) {
			return;
		}
		const handleScroll = () => {
			const container = containerRef;

			if (container) {
				const isScrolledToBottom = container.scrollHeight - container.clientHeight <= container.scrollTop + 1;

				setIsVisible(!isScrolledToBottom);
			}
		};

		containerRef.addEventListener('scroll', handleScroll);

		return () => {
			containerRef.removeEventListener('scroll', handleScroll);
		};
	}, [messageContainerRef]);

	const handleClick = () => {
		const container = messageContainerRef.current;
		if (container) {
			container.scrollTo({
				top: container.scrollHeight - container.clientHeight,
				behavior: 'smooth',
			});
		}
	};

	return (
		<AnimatePresence>
			{isVisible && (
				<motion.button
					type="button"
					initial={{ opacity: 0, y: -10 }}
					animate={{ opacity: 1, y: 0 }}
					exit={{ opacity: 0, y: -10 }}
					transition={{ duration: 0.2 }}
					title="Scroll to bottom"
					onClick={() => handleClick()}
					className="flex items-center justify-center bg-purple-400 outline-none focus:outline-purple-500 focus:ring-0 absolute rounded-full min-w-[2.5rem] min-h-[2.5rem] max-w-[2.5rem] max-h-[2.5rem] mt-auto bottom-20 right-6 ml-auto p-2"
				>
					<CaretDown className="text-white" />
				</motion.button>
			)}
		</AnimatePresence>
	);
}
