// svelte-app/src/lib/modules/chat/components/Chat/MessagesContainer/Typebar.svelte
<script lang="ts">
	import { ulid } from 'ulidx';
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { PaperPlaneTilt, X } from 'phosphor-svelte';

	import Button from '$lib/design-system/Button.svelte';
	import InputGroup from '$lib/design-system/Input/InputGroup.svelte';

	import { connection } from '$lib/modules/chat/contexts/websocket-context/stores/connection';
	import { chatDispatch, chatState } from '$lib/modules/chat/contexts/chat-context/stores/chat';
	import { sendTypingWebSocketEvent } from '$lib/modules/chat/contexts/websocket-context/emmiters/sendTyping';
	import { sendMessageWebSocketEvent } from '$lib/modules/chat/contexts/websocket-context/emmiters/sendMessage';

	import { addMessageAsyncDB } from '../../../../../../services/database/use-cases/add-message';
	import { changeMessageStatusAsyncDB } from '../../../../../../services/database/use-cases/change-message-status';

	import type { Message } from '../../../../../../types/message';
	import { getChatContext } from '$lib/modules/chat/contexts/chat-context/ChatContext.svelte';

	let typeValueManaged = '';

	$: if ($chatState.selectedConversation && $typebarRef) {
		$typebarRef.value = $chatState.selectedConversation?.typeMessage;
	}

	let { typebarRef } = getChatContext();

	$: user = $page.data.session?.user;

	async function sendMessage() {
		if (!user || !$chatState.selectedConversation || !$typebarRef?.value.trim()) return;

		const repliedMessage = (() => {
			if (
				$chatState.selectedConversation?.replyMessage &&
				$chatState.selectedConversation.replyMessage.repliedMessage &&
				typeof $chatState.selectedConversation.replyMessage.repliedMessage === 'object'
			) {
				return {
					...$chatState.selectedConversation?.replyMessage,
					repliedMessage: $chatState.selectedConversation?.replyMessage.repliedMessage.id,
				};
			} else {
				return $chatState.selectedConversation?.replyMessage;
			}
		})();

		const message: Message = {
			id: ulid(),
			content: $typebarRef?.value.trim(),

			writtenAt: new Date(),
			sentAt: null,
			receivedByAllAt: null,
			readByAllAt: null,

			conversationId: $chatState.selectedConversation?.id,
			authorId: user.id,
			repliedMessage: repliedMessage || null,
		};

		addMessageAsyncDB(message).catch(error => {
			console.error(`Error on trying to add the "${message.id}" message at Indexed DB`, error);
		});

		chatDispatch.bringToTop(message.conversationId);

		chatDispatch.addMessage({
			conversationId: $chatState.selectedConversation?.id,
			message,
		});

		if ($connection) {
			sendMessageWebSocketEvent($connection, {
				message: { ...message, readByAllAt: null, receivedByAllAt: null, sentAt: new Date() },
				sender: user.id,
				receiver: $chatState.selectedConversation.id,
			});
		} else {
			console.error('Connection not established!');
		}

		changeMessageStatusAsyncDB({ messageId: message.id, status: 'sent' }).catch(error => {
			console.error(`Error on trying to update the "${message.id}" message status at Indexed DB`, error);
		});

		chatDispatch.saveTypeMessageFromConversation({
			conversationId: $chatState.selectedConversation.id,
			typeMessage: '',
		});

		$typebarRef.value = '';
		typeValueManaged = '';

		chatDispatch.removeReplyMessageFromConversation({ conversationId: $chatState.selectedConversation.id });
	}

	function handleSpreadTypingStatusToConversation(typing: boolean) {
		if ($connection) {
			sendTypingWebSocketEvent($connection, {
				typing,
				conversationId: $chatState.selectedConversation?.id || '',
				authorId: user?.id || '',
			});
		} else {
			console.error('Connection not established!');
		}
	}

	onMount(() => {
		$typebarRef?.addEventListener('input', (e: any) => {
			const value = e.target.value as string;

			if (value && !typeValueManaged) {
				handleSpreadTypingStatusToConversation(true);
			} else if (!value && typeValueManaged) {
				handleSpreadTypingStatusToConversation(false);
			}

			typeValueManaged = $typebarRef?.value || '';
		});
	});
</script>

<div class="flex flex-col gap-2 m-1 mt-auto">
	<!-- <div class="w-full p-2 flex gap-2 bg-black rounded-lg">
		<div class="bg-gray-950 w-full p-2 rounded-md flex flex-col gap-1">
			<span class="text-purple-300 text-xs">{'Name'}</span>
			<span class="text-white text-sm">Conteúdo de mensagem respondida</span>
		</div>

		<button
			type="button"
			title="Cancel reply message"
			on:click={() => /*removeReplyMessageFromConversation({ conversationId: selectedConversation?.id || ''  }) */ {}}
			class="ml-auto bg-gray-900 hover:brightness-125 flex items-center justify-center rounded-full max-w-[2.5rem] min-w-[2.5rem] max-h-[2.5rem] min-h-[2.5rem]"
		>
			<X size={24} color="white" />
		</button>
	</div> -->

	<InputGroup let:Label let:Wrapper className="flex w-full">
		<Label className="sr-only">Type a message</Label>

		<Wrapper className="w-full h-fit">
			<input
				bind:this={$typebarRef}
				type="text"
				class="max-h-[20rem] min-h-[3.5rem] resize-none flex flex-1 py-3 focus:outline-none outline-none hover:ring-1 transition-all dark:ring-gray-700 ring-gray-100 rounded-md dark:bg-gray-900 bg-white dark:text-gray-200 text-gray-700 focus:outline-purple-500 focus:ring-0 dark:placeholder:text-gray-400 placeholder:text-gray-600 w-full px-4"
				placeholder="Type your message"
				autoComplete="off"
				id="typebar-input-id"
			/>

			<Button
				tabIndex={2}
				type="button"
				title="Send message"
				onClick={sendMessage}
				className="p-2 absolute right-3 top-2/4 -translate-y-2/4 min-w-[2.75rem] min-h-[2.75rem] max-w-[2.75rem] max-h-[2.75rem] mt-auto rounded-[10px]"
			>
				<PaperPlaneTilt class="text-white" size={24} />
			</Button>
		</Wrapper>
	</InputGroup>
</div>

// web/src/app/products/chats/components/Chat/MessagesContainer/TypeBar.tsx
'use client';

import { v4 as uuidv4 } from 'uuid';
import { AnimatePresence, motion } from 'framer-motion';
import { useCallback, useEffect, useState } from 'react';
import { PaperPlaneTilt, X } from '@phosphor-icons/react';

import { Input } from '@/@design-system/Input';
import { Button } from '@/@design-system/Button';

import { useWebSocket } from '@/app/products/chats/contexts/websocket-context/hook';

import { Message } from '@/types/message';

import { addMessageAsyncDB } from '@/services/database/use-cases/add-message';
import { changeMessageStatusAsyncDB } from '@/services/database/use-cases/change-message-status';

import { useChat } from '../../../contexts/chat-context/hook';
import { sendTypingWebSocketEvent } from '../../../contexts/websocket-context/emmiters/sendTyping';
import { sendMessageWebSocketEvent } from '../../../contexts/websocket-context/emmiters/sendMessage';

import { useAuth } from '@/contexts/auth-context/hook';
import { useChatsStore } from '../../../contexts/chat-context/stores/chat';

export function TypeBar() {
	const { user } = useAuth();
	const { typebarRef } = useChat();
	const { socket } = useWebSocket();

	const {
		addMessage,
		saveTypeMessageFromConversation,
		removeReplyMessageFromConversation,
		bringToTop,
		selectedConversation,
	} = useChatsStore();

	const [type, setType] = useState('');

	useEffect(() => {
		if (selectedConversation) {
			setType(selectedConversation?.typeMessage || '');
		}
	}, [selectedConversation]);

	const sendMessage = useCallback(async () => {
		if (!user || !selectedConversation || !type.trim()) return;

		const repliedMessage = (() => {
			if (
				selectedConversation?.replyMessage &&
				selectedConversation.replyMessage.repliedMessage &&
				typeof selectedConversation.replyMessage.repliedMessage === 'object'
			) {
				return {
					...selectedConversation?.replyMessage,
					repliedMessage: selectedConversation?.replyMessage.repliedMessage.id,
				};
			} else {
				return selectedConversation?.replyMessage;
			}
		})();

		const message: Message = {
			id: uuidv4(),
			content: type.trim(),

			writtenAt: new Date(),
			sentAt: null,
			receivedByAllAt: null,
			readByAllAt: null,

			conversationId: selectedConversation?.id,
			authorId: user.id,
			repliedMessage: repliedMessage || null,
		};

		addMessageAsyncDB(message);

		bringToTop(message.conversationId);

		addMessage({
			conversationId: selectedConversation?.id,
			message,
		});

		sendMessageWebSocketEvent(socket, {
			message: { ...message, readByAllAt: null, receivedByAllAt: null, sentAt: new Date() },
			sender: user.id,
			receiver: selectedConversation.id,
		});

		changeMessageStatusAsyncDB({ messageId: message.id, status: 'sent' });

		saveTypeMessageFromConversation({ conversationId: selectedConversation.id, typeMessage: '' });
		setType('');
		removeReplyMessageFromConversation({ conversationId: selectedConversation.id });
	}, [
		user,
		selectedConversation,
		type,
		bringToTop,
		addMessage,
		socket,
		saveTypeMessageFromConversation,
		removeReplyMessageFromConversation,
	]);

	function typing(value: string) {
		function handle(typing: boolean) {
			sendTypingWebSocketEvent(socket, {
				typing,
				conversationId: selectedConversation?.id || '',
				authorId: user?.id || '',
			});
		}

		if (value && !type) {
			handle(true);
		} else if (!value && type) {
			handle(false);
		}

		setType(value);
	}

	useEffect(() => {
		const inputRef = typebarRef;

		if (!inputRef.current) return;

		function event(e: KeyboardEvent) {
			if (e.key === 'Enter' && !e.shiftKey) {
				e.preventDefault();
				sendMessage();
			}
		}

		inputRef.current.addEventListener('keydown', event);
		return () => inputRef.current?.removeEventListener('keydown', event);
	}, [sendMessage, typebarRef]);

	useEffect(() => {
		if (selectedConversation?.replyMessage) {
			typebarRef.current?.focus();
		}
	}, [selectedConversation?.replyMessage, typebarRef]);

	return (
		<div className="flex flex-col gap-2 m-1 mt-auto">
			<AnimatePresence mode="popLayout">
				{selectedConversation?.replyMessage && (
					<motion.div
						className="w-full p-2 flex gap-2 bg-black rounded-lg"
						initial={{ opacity: 0, y: 40 }}
						animate={{ opacity: 1, y: 0 }}
						exit={{ opacity: 0, y: 40 }}
					>
						<div className="bg-gray-950 w-full p-2 rounded-md flex flex-col gap-1">
							<span className="text-purple-300 text-xs">{'Name'}</span>
							<span className="text-white text-sm">{selectedConversation?.replyMessage.content}</span>
						</div>

						<button
							type="button"
							title="Cancel reply message"
							onClick={() => removeReplyMessageFromConversation({ conversationId: selectedConversation?.id || '' })}
							className="ml-auto bg-gray-900 hover:brightness-125 flex items-center justify-center rounded-full max-w-[2.5rem] min-w-[2.5rem] max-h-[2.5rem] min-h-[2.5rem]"
						>
							<X size={24} color="white" />
						</button>
					</motion.div>
				)}
			</AnimatePresence>

			<Input.Group className="flex w-full">
				<Input.Label className="sr-only">Type a message</Input.Label>

				<Input.Wrapper className="w-full h-fit">
					<Input
						inputRef={typebarRef}
						type="text"
						className="max-h-[20rem] min-h-[3.5rem] resize-none flex flex-1 py-3 focus:outline-none"
						placeholder="Type your message"
						value={type}
						autoFocus
						autoComplete="off"
						onChange={e => typing(e.target.value)}
					/>

					<Button
						type="button"
						title="Send message"
						onClick={sendMessage}
						className="p-2 absolute right-3 top-2/4 -translate-y-2/4 min-w-[2.75rem] min-h-[2.75rem] max-w-[2.75rem] max-h-[2.75rem] mt-auto rounded-[10px]"
					>
						<PaperPlaneTilt className="text-white" size={24} />
					</Button>
				</Input.Wrapper>
			</Input.Group>
		</div>
	);
}
