// client/src/components/layouts/Main/Chat/MessageContainer/ScrollToBottomButton.tsx
import { useEffect, RefObject, useState } from 'react';
import { ChevronDown } from 'react-feather';
import { useChat } from '../../../../../contexts/chat-context/hook';

import { Button } from '../../../../elements/Button';

interface Props {
	messageContainerRef: RefObject<HTMLDivElement>;
}

export function ScrollToBottomButton({ messageContainerRef }: Props) {
	const [isVisible, setIsVisible] = useState(false);
	const { contactsState } = useChat();

	useEffect(() => {
		const onScroll = () => {
			if (!messageContainerRef.current) return;

			const newVisible =
				messageContainerRef.current.scrollTop + messageContainerRef.current.clientHeight <=
				messageContainerRef.current.scrollHeight;

			setIsVisible(!newVisible);
		};

		messageContainerRef.current?.addEventListener('scroll', onScroll);
		return () => messageContainerRef.current?.removeEventListener('scroll', onScroll);
	}, [messageContainerRef.current]);

	useEffect(() => {
		scrollToBottom();
	}, [contactsState.selectedContact, scrollToBottom]);

	function scrollToBottom(behavior: 'auto' | 'smooth' = 'auto') {
		messageContainerRef.current?.scrollTo({
			behavior,
			top: messageContainerRef.current.scrollHeight,
		});
	}

	return (
		<div className="relative max-h-0 w-full">
			{!isVisible && (
				<Button
					type="button"
					onClick={() => scrollToBottom()}
					className="absolute rounded-full min-w-[3.25rem] min-h-[3.25rem] max-w-[3.25rem] max-h-[3.25rem] mt-auto bottom-8 right-8 ml-auto p-2"
				>
					<ChevronDown className="text-white" />
				</Button>
			)}
		</div>
	);
}

// svelte-app/src/lib/modules/chat/components/Chat/MessagesContainer/ScrollToBottomButton.svelte
<script lang="ts">
   import { onMount } from 'svelte';
   import { ChevronDown } from 'lucide-svelte';

   export let container: HTMLUListElement;

   let isVisible = false;

   onMount(() => {
      const handleScroll = () => {
         if (container) {
            const isScrolledToBottom = container.scrollHeight - container.clientHeight <= container.scrollTop + 1;
            isVisible = !isScrolledToBottom;
         }
      };

      container?.addEventListener('scroll', handleScroll);

      return () => {
         container.removeEventListener('scroll', handleScroll);
      };
   });

   function scrollToBottom() {
      container.scroll({
         top: container.scrollHeight,
         behavior: 'smooth',
      });
   }
</script>

{#if isVisible}
   <button
      type="button"
      title="Scroll to bottom"
      on:click|stopPropagation={scrollToBottom}
      class="absolute bottom-20 right-6 z-20 flex items-center justify-center bg-purple-400 outline-none focus:outline-purple-500 focus:ring-0 rounded-full min-w-[2.5rem] min-h-[2.5rem] max-w-[2.5rem] max-h-[2.5rem] mt-auto ml-auto p-2"
   >
      <ChevronDown class="text-white" />
   </button>
{/if}
