// web/src/@modules/chat/components/Chat/MessagesContainer/TypeBar.tsx
'use client';

import { v4 as uuidv4 } from 'uuid';
import { AnimatePresence, motion } from 'framer-motion';
import { useCallback, useEffect, useState } from 'react';
import { PaperPlaneTilt, X } from '@phosphor-icons/react';

import { Input } from '@/@design-system/Input';
import { Button } from '@/@design-system/Button';

import { Message } from '@/types/message';

import { addMessageAsyncDB } from '@/services/database/use-cases/add-message';
import { changeMessageStatusAsyncDB } from '@/services/database/use-cases/change-message-status';

import { useChat } from '../../../contexts/chat-context/hook';
import { sendTypingWebSocketEvent } from '../../../contexts/websocket-context/emmiters/sendTyping';
import { sendMessageWebSocketEvent } from '../../../contexts/websocket-context/emmiters/sendMessage';

import { useAuth } from '@/contexts/auth-context/hook';
import { useChatsStore } from '../../../contexts/chat-context/stores/chat';

import { useWebSocket } from '@/@modules/chat/contexts/websocket-context/hook';

export function TypeBar() {
	const { user } = useAuth();
	const { typebarRef } = useChat();
	const { socket } = useWebSocket();

	const {
		addMessage,
		saveTypeMessageFromConversation,
		removeReplyMessageFromConversation,
		bringToTop,
		selectedConversation,
	} = useChatsStore();

	const [type, setType] = useState('');

	useEffect(() => {
		if (selectedConversation) {
			setType(selectedConversation?.typeMessage || '');
		}
	}, [selectedConversation]);

	const sendMessage = useCallback(async () => {
		if (!user || !selectedConversation || !type.trim()) return;

		const repliedMessage = (() => {
			if (
				selectedConversation?.replyMessage &&
				selectedConversation.replyMessage.repliedMessage &&
				typeof selectedConversation.replyMessage.repliedMessage === 'object'
			) {
				return {
					...selectedConversation?.replyMessage,
					repliedMessage: selectedConversation?.replyMessage.repliedMessage.id,
				};
			} else {
				return selectedConversation?.replyMessage;
			}
		})();

		const message: Message = {
			id: uuidv4(),
			content: type.trim(),

			writtenAt: new Date(),
			sentAt: null,
			receivedByAllAt: null,
			readByAllAt: null,

			conversationId: selectedConversation?.id,
			authorId: user.id,
			repliedMessage: repliedMessage || null,
		};

		addMessageAsyncDB(message);

		bringToTop(message.conversationId);

		addMessage({
			conversationId: selectedConversation?.id,
			message,
		});

		sendMessageWebSocketEvent(socket, {
			message: { ...message, readByAllAt: null, receivedByAllAt: null, sentAt: new Date() },
			sender: user.id,
			receiver: selectedConversation.id,
		});

		changeMessageStatusAsyncDB({ messageId: message.id, status: 'sent' });

		saveTypeMessageFromConversation({ conversationId: selectedConversation.id, typeMessage: '' });
		setType('');
		removeReplyMessageFromConversation({ conversationId: selectedConversation.id });
	}, [
		user,
		selectedConversation,
		type,
		bringToTop,
		addMessage,
		socket,
		saveTypeMessageFromConversation,
		removeReplyMessageFromConversation,
	]);

	function typing(value: string) {
		function handle(typing: boolean) {
			sendTypingWebSocketEvent(socket, {
				typing,
				conversationId: selectedConversation?.id || '',
				authorId: user?.id || '',
			});
		}

		if (value && !type) {
			handle(true);
		} else if (!value && type) {
			handle(false);
		}

		setType(value);
	}

	useEffect(() => {
		const inputRef = typebarRef;

		if (!inputRef.current) return;

		function event(e: KeyboardEvent) {
			if (e.key === 'Enter' && !e.shiftKey) {
				e.preventDefault();
				sendMessage();
			}
		}

		inputRef.current.addEventListener('keydown', event);
		return () => inputRef.current?.removeEventListener('keydown', event);
	}, [sendMessage, typebarRef]);

	useEffect(() => {
		if (selectedConversation?.replyMessage) {
			typebarRef.current?.focus();
		}
	}, [selectedConversation?.replyMessage, typebarRef]);

	return (
		<div className="flex flex-col gap-2 m-1 mt-auto">
			<AnimatePresence mode="popLayout">
				{selectedConversation?.replyMessage && (
					<motion.div
						className="w-full p-2 flex gap-2 bg-black rounded-lg"
						initial={{ opacity: 0, y: 40 }}
						animate={{ opacity: 1, y: 0 }}
						exit={{ opacity: 0, y: 40 }}
					>
						<div className="bg-gray-950 w-full p-2 rounded-md flex flex-col gap-1">
							<span className="text-purple-300 text-xs">{'Name'}</span>
							<span className="text-white text-sm">{selectedConversation?.replyMessage.content}</span>
						</div>

						<button
							type="button"
							title="Cancel reply message"
							onClick={() => removeReplyMessageFromConversation({ conversationId: selectedConversation?.id || '' })}
							className="ml-auto bg-gray-900 hover:brightness-125 flex items-center justify-center rounded-full max-w-[2.5rem] min-w-[2.5rem] max-h-[2.5rem] min-h-[2.5rem]"
						>
							<X size={24} color="white" />
						</button>
					</motion.div>
				)}
			</AnimatePresence>

			<Input.Group className="flex w-full">
				<Input.Label className="sr-only">Type a message</Input.Label>

				<Input.Wrapper className="w-full h-fit">
					<Input
						inputRef={typebarRef}
						type="text"
						className="max-h-[20rem] min-h-[3.5rem] resize-none flex flex-1 py-3 focus:outline-none"
						placeholder="Type your message"
						value={type}
						autoFocus
						autoComplete="off"
						onChange={e => typing(e.target.value)}
					/>

					<Button
						type="button"
						title="Send message"
						onClick={sendMessage}
						className="p-2 absolute right-3 top-2/4 -translate-y-2/4 min-w-[2.75rem] min-h-[2.75rem] max-w-[2.75rem] max-h-[2.75rem] mt-auto rounded-[10px]"
					>
						<PaperPlaneTilt className="text-white" size={24} />
					</Button>
				</Input.Wrapper>
			</Input.Group>
		</div>
	);
}

// Proxymity-App/src/lib/modules/chat/components/Chat/messages-container/typebar/index.svelte
<script lang="ts">
	import { ulid } from 'ulidx';
	import { page } from '$app/stores';
	import { Send, X } from 'lucide-svelte';

	import Button from '$lib/components/ui/button/button.svelte';
	import InputGroup from '$lib/components/ui/Input/InputGroup.svelte';

	import { chatWorker } from '$lib/modules/chat/workers/db-worker/initializer';
	import { WorkerMethods } from '$lib/modules/chat/workers/db-worker/method-types';
	import {
		messagesContainer,
		typebarRef
	} from '$lib/modules/chat/contexts/chat-context/stores/chat';
	import { webSocketEmitter } from '$lib/modules/chat/contexts/websocket-context/stores/connection';
	import { chatDispatch, chatState } from '$lib/modules/chat/contexts/chat-context/stores/chat';

	import type { ILocalMessage } from '../../../../../../../types/message';
	import { EMessageStatuses } from '../../../../../../../enums/EMessageStatuses';
	import { notificationsDispatch } from '$lib/modules/chat/contexts/chat-context/stores/notification';
	import ReplyMessage from './reply-message.svelte';

	let user = $derived($page.data.session?.user);
	let conversationId = $derived(
		$chatState.conversations[$chatState.selectedConversationIndex]?.id || ''
	);

	let typeValueManaged = $state('');

	async function sendMessage() {
		if (
			!user ||
			!$chatState.conversations[$chatState.selectedConversationIndex] ||
			!$typebarRef?.value.trim()
		)
			return;

		const message: ILocalMessage = {
			id: ulid(),
			content: $typebarRef?.value.trim(),
			writtenAt: new Date(),
			sentAt: null,
			received: { byAllAt: null, users: [] },
			read: { byAllAt: null, users: [] },
			conversationId,
			author: { id: user.id, name: user.name },
			repliedMessage: $chatState.conversations[$chatState.selectedConversationIndex].replyMessage
				? {
						id: $chatState.conversations[$chatState.selectedConversationIndex].replyMessage!.id,
						content:
							$chatState.conversations[$chatState.selectedConversationIndex].replyMessage!.content
					}
				: null
		};

		$chatWorker?.postMessage({ type: WorkerMethods.ADD_MESSAGE, payload: { message } });

		chatDispatch.addMessage({ message });
		chatDispatch.bringToTop(message.conversationId);

		$webSocketEmitter?.sendMessage({
			message,
			isConversationGroup: $chatState.conversations[$chatState.selectedConversationIndex].isGroup
		});

		$chatWorker?.postMessage({
			type: WorkerMethods.CHANGE_MESSAGE_STATUS,
			payload: { messageId: message.id, status: EMessageStatuses.SENT }
		});

		chatDispatch.saveTypeMessageFromConversation({ conversationId, typeMessage: '' });

		$typebarRef.value = '';
		typeValueManaged = '';

		chatDispatch.removeReplyMessageFromConversation({
			conversationId: $chatState.conversations[$chatState.selectedConversationIndex].id
		});

		$messagesContainer?.scroll({ top: $messagesContainer.scrollHeight + 160, behavior: 'smooth' });

		notificationsDispatch.clearLastMessagesHistoryFromConversation(
			$chatState.conversations[$chatState.selectedConversationIndex]
		);
	}

	function handleSpreadTypingStatusToConversation(typing: boolean) {
		$webSocketEmitter?.sendTyping({ conversationId, typing, authorId: user?.id || '' });
	}

	$effect(() => {
		$typebarRef?.addEventListener('input', (e: any) => {
			const value = e.target.value as string;

			if (value && !typeValueManaged) {
				handleSpreadTypingStatusToConversation(true);
			} else if (!value && typeValueManaged) {
				handleSpreadTypingStatusToConversation(false);
			}

			typeValueManaged = $typebarRef?.value || '';
		});

		$typebarRef?.addEventListener('keypress', async (e: KeyboardEvent) => {
			if (e.code === 'Enter') {
				sendMessage();
			}
		});
	});
</script>

<div class="z-[21] m-1 mt-auto flex flex-col gap-2">
	{#if $chatState.conversations[$chatState.selectedConversationIndex]?.replyMessage}
		<ReplyMessage {conversationId} />
	{/if}

	<InputGroup let:Label let:Wrapper className="flex w-full ">
		<Label className="sr-only">Type a message</Label>

		<Wrapper className="w-full h-fit">
			<input
				id="typebar-input-id"
				bind:this={$typebarRef}
				type="text"
				class="flex max-h-[20rem] min-h-[3rem] w-full flex-1 resize-none rounded-md border border-black/30 px-4 py-3 text-primary shadow-sm outline-none ring-gray-700 transition-all placeholder:text-gray-400 hover:ring-1 focus:outline-none focus:outline-purple-500 focus:ring-0"
				placeholder="Type your message"
				autoComplete="off"
			/>

			<Button
				type="button"
				title="Send message"
				onclick={sendMessage}
				class="absolute right-2 top-2/4 mt-auto max-h-[2.75rem] min-h-[2.25rem] min-w-[2.25rem] max-w-[2.75rem] -translate-y-2/4 rounded-[10px] p-2"
			>
				<Send size={18} class="text-white" />
			</Button>
		</Wrapper>
	</InputGroup>
</div>
