// Proxymity-App/src/lib/modules/chat/components/Chat/messages-container/index.svelte
<script lang="ts">
   import { page } from '$app/stores';

   import Text from '$lib/design-system/text.svelte';
   import Heading from '$lib/design-system/heading.svelte';

   import Message from './message.svelte';
   import Typebar from './typebar.svelte';
   import ScrollToBottomButton from './scroll-to-bottom-button.svelte';

   import { chatState, messagesContainer } from '$lib/modules/chat/contexts/chat-context/stores/chat';
   import { notificationsState } from '$lib/modules/chat/contexts/chat-context/stores/notification';

   let userId = $derived($page.data.session?.user.id);

   let firstUnreadMessageId = $derived(
      $notificationsState.lastMessagesHistory.find(
         item => item.conversationId === $chatState.selectedConversation?.id && item.authorId !== userId
      )?.messageId || null
   );

   $effect(() => {
      $chatState.selectedConversation?.messages;

      // Scroll the messages container to bottom using the "auto" behavior
      $messagesContainer?.scroll({ top: $messagesContainer.scrollHeight, behavior: 'auto' });
   });
</script>

<div class="overflow-hidden w-full flex-1 h-full flex flex-col p-1 relative max-w-5xl mx-auto">
   <ul class="flex flex-col gap-2 overflow-auto p-4" bind:this={$messagesContainer}>
      {#if !$chatState.selectedConversation?.hasMessagesFetched}
         <Text size="md">Loading messages...</Text>
      {/if}

      {#if $chatState.selectedConversation?.messages.length === 0}
         <div class="flex-1 flex items-center justify-center flex-col gap-3 pointer-events-none">
            <img src="/no-messages.svg" alt="No message" class="w-[15rem]" />
            <Heading size="md" class="opacity-80">No messages have been sent yet...</Heading>
         </div>
      {:else if $chatState.selectedConversation?.messages}
         {#each $chatState.selectedConversation?.messages as message, i (message.id)}
            {#if firstUnreadMessageId === message.id}
               <div class="flex items-center gap-4 w-full">
                  <div class="w-full h-[2px] rounded-sm bg-purple-300"></div>
                  <span class="text-purple-300 whitespace-nowrap">Unread messages</span>
                  <div class="w-full h-[2px] rounded-sm bg-purple-300"></div>
               </div>
            {/if}

            <Message {message} previousMessage={$chatState.selectedConversation?.messages?.[i - 1]} messageIndex={i} />
         {/each}
      {/if}
   </ul>

   <Typebar />
</div>

<ScrollToBottomButton />

// web/src/@modules/chat/components/Chat/MessagesContainer/index.tsx
/* eslint-disable @next/next/no-img-element */
import { useEffect, useRef } from 'react';

import { Message } from './Message';
import { TypeBar } from './TypeBar';

import { Heading } from '@/@design-system/Heading';

import { ScrollToBottomButton } from './ScrollToBottomButton';
import { useChatsStore } from '../../../contexts/chat-context/stores/chat';

export function MessagesContainer() {
	const isFirstAccess = useRef(true);
	const messageContainerRef = useRef<HTMLUListElement>(null);

	const { selectedConversation } = useChatsStore();
	const conversationMessages = selectedConversation?.messages;

	useEffect(() => {
		isFirstAccess.current = true;
	}, [selectedConversation]);

	useEffect(() => {
		const container = messageContainerRef.current;

		if (container && container.scrollHeight > container.clientHeight) {
			container.scrollTo({
				top: container.scrollHeight,
				behavior: isFirstAccess.current ? 'auto' : 'smooth',
			});

			isFirstAccess.current = false;
		}
	}, [conversationMessages]);

	return (
		<div className="overflow-hidden w-full flex-1 h-full flex flex-col p-1 relative">
			<ul className="flex flex-col gap-2 overflow-auto p-4" ref={messageContainerRef}>
				{conversationMessages?.length === 0 ? (
					<div className="flex-1 flex items-center justify-center flex-col gap-3 pointer-events-none">
						<img src="/no-messages.svg" alt="No message" className="w-[25rem]" />
						<Heading size="sm" className="opacity-80">
							No messages have been sent yet...
						</Heading>
					</div>
				) : (
					conversationMessages?.map((message, i) => (
						<Message key={message.id} message={message} previousMessage={conversationMessages?.[i - 1]} />
					))
				)}
			</ul>

			<ScrollToBottomButton messageContainerRef={messageContainerRef} />
			<TypeBar />
		</div>
	);
}
