// Proxymity-App/src/lib/modules/chat/components/Chat/messages-container/message.svelte
<script lang="ts">
   import clsx from 'clsx';
   import { onMount } from 'svelte';
   import { page } from '$app/stores';
   import { fly } from 'svelte/transition';
   import { Clock, InfoIcon, Share } from 'lucide-svelte';

   import * as Avatar from '$lib/design-system/avatar';

   import { chatWorker } from '$lib/modules/chat/workers/db-worker/initializer';
   import { typebarRef } from '$lib/modules/chat/contexts/chat-context/stores/chat';
   import { WorkerMethods } from '$lib/modules/chat/workers/db-worker/method-types';
   import { getStatusFromMessage } from '$lib/modules/chat/services/getStatusFromMessage';
   import { chatDispatch, chatState } from '$lib/modules/chat/contexts/chat-context/stores/chat';

   import type { ILocalMessage } from '../../../../../../types/message';
   import { EMessageStatuses } from '../../../../../../enums/EMessageStatuses';
   import { appColor } from '../../../../../../contexts/theme/store';

   type Props = {
      message: ILocalMessage;
      previousMessage: ILocalMessage;
      messageIndex: number;
      selectMessage: () => void;
   };

   let { message, messageIndex, previousMessage, selectMessage }: Props = $props();

   let messageRef: HTMLLIElement;

   let isHighlighting = $state(false);
   let showMessageStatus = $state(false);
   let isMessageConfigVisible = $state(false);

   const previousIsFromUser = previousMessage?.author?.id === message.author?.id;
   const formatter = Intl.DateTimeFormat('pt-br', { hour: 'numeric', minute: 'numeric' });

   let session = $derived($page.data.session);
   let isMine = $derived(message.author?.id === session?.user?.id);
   let timeToShow = $derived(formatter.format(new Date(message.writtenAt)));

   let status: EMessageStatuses = $derived.by(() => {
      if (message.read.byAllAt !== null) return EMessageStatuses.READ;
      if (message.received.byAllAt !== null) return EMessageStatuses.RECEIVED;
      if (message.sentAt !== null) return EMessageStatuses.SENT;

      return EMessageStatuses.WROTE;
   });

   // $effect(() => {
   //    if (message.read.byAllAt !== null) status = EMessageStatuses.READ;
   //    if (message.received.byAllAt !== null) status = EMessageStatuses.RECEIVED;
   //    if (message.sentAt !== null) status = EMessageStatuses.SENT;

   //    status = EMessageStatuses.WROTE;
   // });

   type EventHandler = CustomEventInit<
      | {
           messageStatus: EMessageStatuses.SENT | EMessageStatuses.RECEIVED;
           messageId: string;
           conversationId: string;
           userId: string;
           type: 'message_status';
           appliedForAll: boolean;
        }
      | {
           type: 'highlight';
           messageId: string;
        }
   >;

   function messageEventHandler(event: EventHandler) {
      if (!event.detail) return;

      if (event.detail.type === 'message_status') {
         const { messageId, messageStatus, conversationId, userId, appliedForAll } = event.detail;

         if (messageStatus && messageId && conversationId) {
            // status = messageStatus;

            chatDispatch.updateConversationMessageStatus({
               conversationId,
               messageId,
               status: messageStatus,
               userId,
               appliedForAll,
            });
            $chatWorker?.postMessage({
               type: WorkerMethods.CHANGE_MESSAGE_STATUS,
               payload: { messageId: messageId, status: messageStatus },
            });
         }
      }

      if (event.detail.type === 'highlight') {
         isHighlighting = true;

         setTimeout(() => {
            isHighlighting = false;
         }, 2000);
      }
   }

   async function handleWithUpdateOfMessageStatus() {
      showMessageStatus = true;

      if ($chatState.selectedConversation?.isGroup) {
         const response = await getStatusFromMessage(
            { messageId: message.id, conversationId: message.conversationId },
            { accessToken: session?.accessToken || '' }
         );

         chatDispatch.updateUsersFromMessageStatus({
            message,
            users: response.map(item => ({ readAt: item.readAt, receivedAt: item.receivedAt, userId: item.userId })),
         });
      } else {
         chatDispatch.updateUsersFromMessageStatus({ message, users: [] });
      }

      // setTimeout(() => {
      //    showMessageStatus = false;
      // }, 5000);
   }

   function scrollToRepliedMessage() {
      if (message.repliedMessage) {
         document.getElementById(message.repliedMessage.id)?.scrollIntoView({ block: 'center' });

         const messageEvent = new CustomEvent(message.repliedMessage.id, {
            detail: { type: 'highlight', messageId: message.id },
         });

         dispatchEvent(messageEvent);
      }
   }

   onMount(() => {
      addEventListener(message.id, messageEventHandler);
      return () => removeEventListener(message.id, messageEventHandler);
   });
</script>

<li
   id={message.id}
   data-highlight={isHighlighting}
   class="flex flex-col gap-1 rounded-[1rem] w-full data-[highlight=true]:animate-pulse data-[highlight=true]:bg-gray-800 data-[highlight=true]:p-3 transition-all"
   bind:this={messageRef}
   oncontextmenu={() => selectMessage()}
   onfocus={() => {
      isMessageConfigVisible = true;
   }}
   onblur={() => {
      isMessageConfigVisible = false;
   }}
   onmouseover={() => {
      isMessageConfigVisible = true;
   }}
   onmouseleave={() => {
      isMessageConfigVisible = false;
   }}
>
   <div
      class={clsx('flex items-center gap-3 sticky z-20 bg-gray-900 transition-colors p-1 px-2 rounded-full w-fit -top-3', {
         'ml-auto': isMine,
      })}
   >
      {#if !isMine && !previousIsFromUser}
         <Avatar.Image src="https://github.com/shadcn.png" username={message.author.name} />

         <span class="text-gray-200 transition-colors text-xs">{message.author.name}</span>
      {/if}

      <span class="text-gray-300 transition-colors text-xs flex items-center gap-2">
         {#if isMine && status === EMessageStatuses.WROTE}
            <Clock size={13} class="text-gray-100 transition-colors" />
         {:else if isMine}
            <div
               title={status ? status.toString() : '...'}
               class={clsx('w-6 h-3 rounded-full flex items-center p-[2px] transition-all', {
                  'justify-end bg-transparent': status === EMessageStatuses.SENT,
                  'justify-end bg-gray-600 ': status === EMessageStatuses.RECEIVED,
                  'justify-start bg-purple-500': status === EMessageStatuses.READ,
               })}
            >
               <div class="rounded-full w-2 h-2 bg-white transition-all"></div>
            </div>
         {/if}

         {timeToShow}
      </span>
   </div>

   <div class={clsx('flex items-center gap-2 relative', { 'flex-row-reverse': isMine })}>
      <div
         class={clsx(
            'w-fit rounded-[6px] max-w-[80%] border border-gray-800 text-white font-light text-sm shadow z-[13] p-1 min-w-[100px]',
            {
               'bg-gradient-to-r from-[#5852D6] to-transparent rounded-tl-none': !isMine,
               'bg-gradient-to-l from-[#9D12E0dd] to-transparent rounded-tr-none': isMine && $appColor === 'purple',
               'bg-blue-500 rounded-tr-none': isMine && $appColor === 'blue',
               'bg-red-500 rounded-tr-none': isMine && $appColor === 'red',
               'bg-green-600 rounded-tr-none': isMine && $appColor === 'green',
               'bg-gray-800 rounded-tr-none': isMine && $appColor === 'gray',
            }
         )}
      >
         {#if message.repliedMessage}
            <button
               type="button"
               title="Show replied message on chat"
               onclick={scrollToRepliedMessage}
               class="bg-black items-start cursor-pointer truncate transition-colors p-2 rounded-[8px] w-full flex flex-col gap-1"
            >
               <span class="text-purple-300 text-xs break-words truncate text-start w-full">{message.author.name}</span>
               <span class="text-gray-200 text-sm line-clamp-2 text-start break-words truncate flex w-full">
                  {message.repliedMessage.content}
               </span>
            </button>
         {/if}

         <p class="p-1 break-words">{message.content}</p>
      </div>

      {#if isMessageConfigVisible}
         <button
            type="button"
            transition:fly={{ duration: 300, x: isMine ? 30 : -30, opacity: 0 }}
            class="p-2 bg-gray-700 shadow-lg z-10 rounded-full active:scale-95 transition-all hover:brightness-90"
            onclick={() => {
               $typebarRef?.focus();
               chatDispatch.setReplyMessageFromConversation({ conversationId: message.conversationId, message });
            }}
         >
            <Share size={12} color="white" />
         </button>
      {/if}

      {#if showMessageStatus}
         <div
            class={clsx('flex flex-col gap-1 p-2 bg-gray-800 rounded-md absolute z-50 shadow-lg', {
               'left-0': isMine,
               'right-0': !isMine,
            })}
         >
            <button type="button" class="text-white flex gap-4 items-center px-4 py-2 hover:brightness-150 transition-all">
               <InfoIcon size={16} class="text-white" />
               Detalhes
            </button>
         </div>
      {/if}
   </div>
</li>

// web/src/@modules/chat/components/Chat/MessagesContainer/Message.tsx
import clsx from 'clsx';
import Image from 'next/image';
import { AnimatePresence, motion } from 'framer-motion';
import { Clock, ShareFat } from '@phosphor-icons/react';
import { Fragment, useEffect, useState } from 'react';

import { Message } from '@/types/message';

import { useAuth } from '@/contexts/auth-context/hook';
import { Events, ExtractPayloadType } from '../../../contexts/websocket-context/handler';
import { useChatsStore } from '../../../contexts/chat-context/stores/chat';

import { changeMessageStatusAsyncDB } from '@/services/database/use-cases/change-message-status';

interface Props {
	previousMessage?: Message;
	message: Message;
}

const formatter = Intl.DateTimeFormat('pt-br', { hour: 'numeric', minute: 'numeric' });

export function Message({ message, previousMessage }: Props) {
	const { user } = useAuth();
	const { updateConversationMessageStatus, setReplyMessageFromConversation } = useChatsStore();
	const [isMessageConfigVisible, setIsMessageConfigVisible] = useState(false);
	const [status, setStatus] = useState<'sent' | 'received' | 'read' | 'wrote'>(() => {
		if (message.readByAllAt !== null) return 'read';
		if (message.receivedByAllAt !== null) return 'received';
		if (message.sentAt !== null) return 'sent';

		return 'wrote';
	});

	const selectTimeToShow = (isMine: boolean, message: Message) =>
		isMine
			? formatter.format(new Date(message.writtenAt))
			: message.receivedByAllAt && new Date(message.receivedByAllAt) !== null
			? formatter.format(new Date(message.receivedByAllAt))
			: null;

	const isMine = message.authorId === user?.id;
	const previousIsFromUser = previousMessage?.authorId === message.authorId;

	const timeToShow = selectTimeToShow(isMine, message);

	//🟡 Receive a message that has the status changed, and update it on react state and IndexedDB
	useEffect(() => {
		function handler(event: CustomEventInit<ExtractPayloadType<'receive_message_status', Events>>) {
			if (!event.detail) {
				return;
			}

			const { messageId, status: newStatus, conversationId } = event.detail;

			if (newStatus && messageId && conversationId) {
				setStatus(newStatus);
				updateConversationMessageStatus({ conversationId, messageId: message.id, status: newStatus });
				changeMessageStatusAsyncDB({ messageId: messageId, status: newStatus });
			}
		}

		addEventListener(message.id, handler);
		return () => removeEventListener(message.id, handler);
	}, [message.id, updateConversationMessageStatus]);

	//🟡 Receive the "read" message status from another user, and update it at state
	useEffect(() => {
		function handler(event: CustomEventInit<ExtractPayloadType<'receive_read_message', Events>>) {
			const conversationId = event.detail?.conversationId || '';

			if (conversationId === message.conversationId && message.readByAllAt === null) {
				console.log('@ws.receive_message_status', conversationId);
				setStatus('read');
			}
		}

		addEventListener('@ws.receive_read_message', handler);
		return () => removeEventListener('@ws.receive_read_message', handler);
	}, [message.conversationId, message.readByAllAt]);

	return (
		<motion.li
			initial={{ opacity: 0, x: 10 }}
			animate={{ opacity: 1, x: 0 }}
			exit={{ opacity: 0, x: 10 }}
			onMouseOver={() => setIsMessageConfigVisible(true)}
			onMouseOut={() => setIsMessageConfigVisible(false)}
			className="flex flex-col gap-1  rounded-[1rem] w-full"
		>
			<div
				className={clsx(
					'flex items-center gap-3 sticky dark:bg-gray-900 bg-white transition-colors p-1 px-2 rounded-full w-fit -top-3',
					{
						'ml-auto': isMine,
					}
				)}
			>
				{!isMine && !previousIsFromUser && (
					<Fragment>
						<Image
							src="https://github.com/diego3g.png"
							alt="User Photo"
							width={30}
							height={30}
							className="min-w-[30px] min-h-[30px] rounded-full z-0 shadow-xl"
						/>
						<span className="dark:text-gray-200 text-gray-700 transition-colors text-xs">Diego</span>
					</Fragment>
				)}

				<span className="dark:text-gray-300 text-gray-700 transition-colors text-xs ml-2 flex items-center gap-2">
					{isMine &&
						(status === 'wrote' ? (
							<Clock size={13} className="dark:text-gray-100 text-gray-600 transition-colors" />
						) : (
							<div
								title={status}
								className={clsx('w-6 h-3 rounded-full flex items-center p-[2px] transition-all', {
									'justify-end bg-transparent': status === 'sent',
									'justify-end dark:bg-gray-600 bg-gray-300': status === 'received',
									'justify-start bg-purple-500': status === 'read',
								})}
							>
								<div className="rounded-full w-2 h-2 bg-white transition-all" />
							</div>
						))}

					{timeToShow}
				</span>
			</div>

			<div className={clsx('flex items-center gap-2', { 'flex-row-reverse': isMine })}>
				<div
					className={clsx('w-fit rounded-[12px] text-white font-light text-sm shadow z-[13] p-1 min-w-[100px]', {
						'bg-gray-950 rounded-tl-none': !isMine,
						'bg-purple-500 rounded-tr-none': isMine,
					})}
				>
					{message.repliedMessage && (
						<div
							className={clsx('dark:bg-black bg-white transition-colors p-2 rounded-[8px] w-full flex flex-col', {
								'ml-auto': isMine,
							})}
						>
							<span className="text-purple-300 text-xs">{'Typescript'}</span>
							<span className="text-gray-200 text-sm">
								{typeof message.repliedMessage === 'object' ? message.repliedMessage?.content : null}
							</span>
						</div>
					)}
					<p className="p-1">{message.content}</p>
				</div>

				<AnimatePresence>
					{isMessageConfigVisible && (
						<motion.button
							className="p-2 bg-gray-700 shadow-lg z-10 rounded-full"
							initial={{ opacity: 0, x: isMine ? 10 : -10 }}
							animate={{ opacity: 1, x: 0 }}
							exit={{ opacity: 0, x: isMine ? 10 : -10 }}
							onClick={() => setReplyMessageFromConversation({ conversationId: message.conversationId, message })}
						>
							<ShareFat size={16} color="white" weight="fill" />
						</motion.button>
					)}
				</AnimatePresence>
			</div>
		</motion.li>
	);
}
