// web/src/app/products/chats/components/Chat/MessagesContainer/ScrollToBottomButton.tsx
import { CaretDown } from '@phosphor-icons/react';
import { useEffect, RefObject, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';

interface Props {
	messageContainerRef: RefObject<HTMLUListElement>;
}

export function ScrollToBottomButton({ messageContainerRef }: Props) {
	const [isVisible, setIsVisible] = useState(false);

	useEffect(() => {
		const containerRef = messageContainerRef.current;

		if (!containerRef) {
			return;
		}
		const handleScroll = () => {
			const container = containerRef;

			if (container) {
				const isScrolledToBottom = container.scrollHeight - container.clientHeight <= container.scrollTop + 1;

				setIsVisible(!isScrolledToBottom);
			}
		};

		containerRef.addEventListener('scroll', handleScroll);

		return () => {
			containerRef.removeEventListener('scroll', handleScroll);
		};
	}, [messageContainerRef]);

	const handleClick = () => {
		const container = messageContainerRef.current;
		if (container) {
			container.scrollTo({
				top: container.scrollHeight - container.clientHeight,
				behavior: 'smooth',
			});
		}
	};

	return (
		<AnimatePresence>
			{isVisible && (
				<motion.button
					type="button"
					initial={{ opacity: 0, y: -10 }}
					animate={{ opacity: 1, y: 0 }}
					exit={{ opacity: 0, y: -10 }}
					transition={{ duration: 0.2 }}
					title="Scroll to bottom"
					onClick={() => handleClick()}
					className="flex items-center justify-center bg-purple-400 outline-none focus:outline-purple-500 focus:ring-0 absolute rounded-full min-w-[2.5rem] min-h-[2.5rem] max-w-[2.5rem] max-h-[2.5rem] mt-auto bottom-20 right-6 ml-auto p-2"
				>
					<CaretDown className="text-white" />
				</motion.button>
			)}
		</AnimatePresence>
	);
}

// Proxymity-App/src/lib/modules/chat/components/Chat/messages-container/scroll-to-bottom-button.svelte
<script lang="ts">
	import { scale } from 'svelte/transition';
	import { ChevronDown } from 'lucide-svelte';

	import { messagesContainer } from '$lib/modules/chat/contexts/chat-context/stores/chat';

	let isVisible = false;

	$: handleScroll = () => {
		if ($messagesContainer) {
			const isScrolledToBottom =
				$messagesContainer.scrollHeight - $messagesContainer.clientHeight <=
				$messagesContainer.scrollTop + 1;
			isVisible = !isScrolledToBottom;
		}
	};

	$: if ($messagesContainer) {
		$messagesContainer?.addEventListener('scroll', handleScroll);
	}

	function scrollToBottom() {
		$messagesContainer?.scroll({ top: $messagesContainer.scrollHeight, behavior: 'smooth' });
	}
</script>

{#if isVisible}
	<button
		transition:scale={{ duration: 300, start: 0, opacity: 0.5 }}
		type="button"
		title="Scroll to bottom"
		on:click|stopPropagation={scrollToBottom}
		class="absolute bottom-24 right-8 z-30 ml-auto mt-auto flex max-h-[1.75rem] min-h-[1.75rem] min-w-[1.75rem] max-w-[1.75rem] items-center justify-center rounded-full bg-purple-400 p-1 outline-none focus:outline-purple-500 focus:ring-0"
	>
		<ChevronDown class="text-white" />
	</button>
{/if}
