// svelte-app/src/lib/modules/chat/components/Chat/index.svelte
<script lang="ts">
	import ChatHeader from './ChatHeader.svelte';
	import MessagesContainer from './MessagesContainer/index.svelte';
</script>

<section
	class="dark:bg-gray-900 bg-gray-200 transition-all rounded-[10px] overflow-hidden w-full flex-1 flex flex-col bg-[url('/chat-background.svg')] bg-cover bg-no-repeat"
>
	<ChatHeader />
	<MessagesContainer />
</section>

// client/src/components/layouts/Main/Chat/index.tsx
import { Fragment, useRef } from 'react';

import { useChat } from '../../../../contexts/chat-context/hook';
import { ChatHeader } from './ChatHeader';
import { MessageContainer } from './MessageContainer';
import { ScrollToBottomButton } from './MessageContainer/ScrollToBottomButton';
import { TypeBar } from './TypeBar';

export function Chat() {
	const { contactsState } = useChat();
	const container = useRef<HTMLDivElement>(null);

	return (
		<main className="flex flex-col flex-1 bg-[url('./src/assets/chat-background.svg')] bg-cover bg-no-repeat rounded-lg overflow-hidden">
			{contactsState.selectedContact && (
				<Fragment>
					<ChatHeader />

					<section className="flex flex-1 w-full flex-col max-w-[40rem] mx-auto overflow-y-auto">
						<MessageContainer refContainer={container} />
						<TypeBar />
					</section>

					<ScrollToBottomButton messageContainerRef={container} />
				</Fragment>
			)}
		</main>
	);
}
