// svelte-app/src/lib/modules/chat/components/Chat/MessagesContainer/Typebar.svelte
<script lang="ts">
	import { ulid } from 'ulidx';
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { PaperPlaneTilt, X } from 'phosphor-svelte';

	import Button from '$lib/design-system/Button.svelte';
	import InputGroup from '$lib/design-system/Input/InputGroup.svelte';

	import { connection } from '$lib/modules/chat/contexts/websocket-context/stores/connection';
	import { chatDispatch, chatState } from '$lib/modules/chat/contexts/chat-context/stores/chat';
	import { sendTypingWebSocketEvent } from '$lib/modules/chat/contexts/websocket-context/emmiters/sendTyping';
	import { sendMessageWebSocketEvent } from '$lib/modules/chat/contexts/websocket-context/emmiters/sendMessage';

	import { addMessageAsyncDB } from '../../../../../../services/database/use-cases/add-message';
	import { changeMessageStatusAsyncDB } from '../../../../../../services/database/use-cases/change-message-status';

	import type { Message } from '../../../../../../types/message';
	import { getChatContext } from '$lib/modules/chat/contexts/chat-context/ChatContext.svelte';

	let typeValueManaged = '';

	$: if ($chatState.selectedConversation && $typebarRef) {
		$typebarRef.value = $chatState.selectedConversation?.typeMessage;
	}

	let { typebarRef } = getChatContext();

	$: user = $page.data.session?.user;

	async function sendMessage() {
		if (!user || !$chatState.selectedConversation || !$typebarRef?.value.trim()) return;

		const repliedMessage = (() => {
			if (
				$chatState.selectedConversation?.replyMessage &&
				$chatState.selectedConversation.replyMessage.repliedMessage &&
				typeof $chatState.selectedConversation.replyMessage.repliedMessage === 'object'
			) {
				return {
					...$chatState.selectedConversation?.replyMessage,
					repliedMessage: $chatState.selectedConversation?.replyMessage.repliedMessage.id,
				};
			} else {
				return $chatState.selectedConversation?.replyMessage;
			}
		})();

		const message: Message = {
			id: ulid(),
			content: $typebarRef?.value.trim(),

			writtenAt: new Date(),
			sentAt: null,
			receivedByAllAt: null,
			readByAllAt: null,

			conversationId: $chatState.selectedConversation?.id,
			authorId: user.id,
			repliedMessage: repliedMessage || null,
		};

		addMessageAsyncDB(message).catch(error => {
			console.error(`Error on trying to add the "${message.id}" message at Indexed DB`, error);
		});

		chatDispatch.bringToTop(message.conversationId);

		chatDispatch.addMessage({
			conversationId: $chatState.selectedConversation?.id,
			message,
		});

		if ($connection) {
			sendMessageWebSocketEvent($connection, {
				message: { ...message, readByAllAt: null, receivedByAllAt: null, sentAt: new Date() },
				sender: user.id,
				receiver: $chatState.selectedConversation.id,
			});
		} else {
			console.error('Connection not established!');
		}

		changeMessageStatusAsyncDB({ messageId: message.id, status: 'sent' }).catch(error => {
			console.error(`Error on trying to update the "${message.id}" message status at Indexed DB`, error);
		});

		chatDispatch.saveTypeMessageFromConversation({
			conversationId: $chatState.selectedConversation.id,
			typeMessage: '',
		});

		$typebarRef.value = '';
		typeValueManaged = '';

		chatDispatch.removeReplyMessageFromConversation({ conversationId: $chatState.selectedConversation.id });
	}

	function handleSpreadTypingStatusToConversation(typing: boolean) {
		if ($connection) {
			sendTypingWebSocketEvent($connection, {
				typing,
				conversationId: $chatState.selectedConversation?.id || '',
				authorId: user?.id || '',
			});
		} else {
			console.error('Connection not established!');
		}
	}

	onMount(() => {
		$typebarRef?.addEventListener('input', (e: any) => {
			const value = e.target.value as string;

			if (value && !typeValueManaged) {
				handleSpreadTypingStatusToConversation(true);
			} else if (!value && typeValueManaged) {
				handleSpreadTypingStatusToConversation(false);
			}

			typeValueManaged = $typebarRef?.value || '';
		});
	});
</script>

<div class="flex flex-col gap-2 m-1 mt-auto">
	<!-- <div class="w-full p-2 flex gap-2 bg-black rounded-lg">
		<div class="bg-gray-950 w-full p-2 rounded-md flex flex-col gap-1">
			<span class="text-purple-300 text-xs">{'Name'}</span>
			<span class="text-white text-sm">Conteúdo de mensagem respondida</span>
		</div>

		<button
			type="button"
			title="Cancel reply message"
			on:click={() => /*removeReplyMessageFromConversation({ conversationId: selectedConversation?.id || ''  }) */ {}}
			class="ml-auto bg-gray-900 hover:brightness-125 flex items-center justify-center rounded-full max-w-[2.5rem] min-w-[2.5rem] max-h-[2.5rem] min-h-[2.5rem]"
		>
			<X size={24} color="white" />
		</button>
	</div> -->

	<InputGroup let:Label let:Wrapper className="flex w-full">
		<Label className="sr-only">Type a message</Label>

		<Wrapper className="w-full h-fit">
			<input
				bind:this={$typebarRef}
				type="text"
				class="max-h-[20rem] min-h-[3.5rem] resize-none flex flex-1 py-3 focus:outline-none outline-none hover:ring-1 transition-all dark:ring-gray-700 ring-gray-100 rounded-md dark:bg-gray-900 bg-white dark:text-gray-200 text-gray-700 focus:outline-purple-500 focus:ring-0 dark:placeholder:text-gray-400 placeholder:text-gray-600 w-full px-4"
				placeholder="Type your message"
				autoComplete="off"
				id="typebar-input-id"
			/>

			<Button
				tabIndex={2}
				type="button"
				title="Send message"
				onClick={sendMessage}
				className="p-2 absolute right-3 top-2/4 -translate-y-2/4 min-w-[2.75rem] min-h-[2.75rem] max-w-[2.75rem] max-h-[2.75rem] mt-auto rounded-[10px]"
			>
				<PaperPlaneTilt class="text-white" size={24} />
			</Button>
		</Wrapper>
	</InputGroup>
</div>

// client/src/components/layouts/Main/Chat/TypeBar.tsx
import { FormEvent, useRef, useState } from 'react';
import { Mic, Send } from 'react-feather';
import { v4 as uuidv4 } from 'uuid';
import { useChat } from '../../../../contexts/chat-context/hook';
import { useUser } from '../../../../contexts/user-context/reducers/hook';
import { addMessageAsyncDB } from '../../../../services/database/use-cases/add-message';
import { Message } from '../../../../types/message';

export function TypeBar() {
	const textAreaRef = useRef<HTMLTextAreaElement>(null);
	const [type, setType] = useState('');

	const { userState } = useUser();
	const { contactsState, messagesDispatch } = useChat();

	function adjustTextAreaHeight(value: string) {
		if (!textAreaRef?.current) return;

		if (value === '') textAreaRef.current.style.height = '3.5rem';
		else textAreaRef.current.style.height = `${textAreaRef.current.scrollHeight / 16}rem`;

		setType(value);
	}

	async function sendMessage(event: FormEvent) {
		event.preventDefault();

		if (!userState.data || !contactsState.selectedContact) return;

		const message: Message = {
			id: uuidv4(),
			content: type,
			readAt: null,
			writtenAt: new Date(),
			receivedAt: null,
			sentAt: null,
			authorId: userState.data.id,
			recipientId: contactsState.selectedContact?.id,
		};

		addMessageAsyncDB(message);

		messagesDispatch({
			type: 'ADD_MESSAGE',
			payload: { contactId: contactsState.selectedContact?.id, message },
		});

		setType('');
	}

	return (
		<div className="mb-3 flex gap-4 px-4">
			<form
				action=""
				className="w-full flex flex-1 gap-2"
				onSubmit={sendMessage}
			>
				<textarea
					ref={textAreaRef}
					placeholder="Message"
					className="rounded-lg flex flex-1 p-4 max-h-[20rem] min-h-[2rem] h-14 transition-all resize-none bg-gray-900 text-white focus:ring-2 focus:ring-purple-600 outline-none text-justify"
					value={type}
					onChange={e => adjustTextAreaHeight(e.target.value)}
				/>

				<button
					type="submit"
					title="Send message"
					className="rounded-full flex items-center justify-center bg-blue-500 min-w-[3.5rem] min-h-[3.5rem] max-w-[3.5rem] max-h-[3.5rem] mt-auto"
				>
					<Send className="text-lg text-white" />
				</button>
			</form>

			<button
				type="button"
				title="Record an audio"
				className="rounded-full flex items-center justify-center bg-blue-500 min-w-[3.5rem] min-h-[3.5rem] max-w-[3.5rem] max-h-[3.5rem] mt-auto"
				onClick={() => {}}
			>
				<Mic className="text-lg text-white" />
			</button>
		</div>
	);
}
