// web/src/app/products/chats/components/Header/index.tsx
'use client';

import Image from 'next/image';
import { useState } from 'react';
import { Moon, Sun } from '@phosphor-icons/react';

import { Switch } from '@design-system/Switch';

import { NotificationButton } from './NotificationButton';
import { Routes } from './Routes';
import { Profile } from './Profile';

export function Header() {
	const [theme, setTheme] = useState('dark');

	return (
		<header className="bg-gray-800  h-[80px] border-b border-solid border-gray-900">
			<div className="max-w-[1366px] flex items-center gap-8 px-6 m-auto">
				<Image src="/horizontal-logo.svg" alt="ProxyMity Logo" width={166} height={49} priority />
				<Routes />

				<div className="flex items-center gap-4 ml-auto">
					<Switch
						checked={theme === 'light'}
						onChange={value => setTheme(value ? 'light' : 'dark')}
						checkedComponent={<Moon className="text-gray-500" size={16} />}
						nonCheckedComponent={<Sun className="text-gray-500" size={16} />}
					/>

					<NotificationButton />
				</div>

				<Profile />
			</div>
		</header>
	);
}

// svelte-app/src/lib/application/Header/Header.svelte
<script>
   import Routes from './Routes.svelte';
   import Profile from './Profile.svelte';
</script>

<header
   class="dark:bg-black bg-gray-100 min-h-[70px] border-b border-solid dark:border-gray-900 border-gray-200 flex items-center w-full transition-colors"
>
   <div class="max-w-[1980px] flex items-center gap-8 px-6 m-auto w-full">
      <img src="/horizontal-logo.svg" alt="ProxyMity Logo" width={166} height={49} />

      <Routes />

      <div class="flex items-center gap-4 ml-auto">
         <!-- <NotificationButton /> -->
      </div>

      <Profile />
   </div>
</header>
